# volumes:
volumes:
  movies-data:
    external: true

services:
  mongo:
    image: mongo:5
    volumes:
      - movies-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=movies_user
      - MONGO_INITDB_ROOT_PASSWORD=movies_password
  fastapi:
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    environment:
      - MONGO_USER=movies_user
      - MONGO_PASSWORD=movies_password
      - MONGO_HOST=mongo
      - MONGO_DB=movies-db
      - SIGNING_KEY=jP7AhzKiVc2tSovLyKVqvqqabTiV0EMY9QXZoKO0Qjc

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: ${REACT_APP_SAMPLE_SERVICE_API_HOST}
